services:
  - type: web
    name: donation-system-backend
    runtime: docker
    plan: free
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://neondb_owner:npg_mAJxKRSr03ap@ep-wispy-cloud-ahm1khc2-pooler.c-3.us-east-1.aws.neon.tech:5432/neondb?sslmode=require&options=endpoint%3Dep-wispy-cloud-ahm1khc2-pooler
      - key: SPRING_DATASOURCE_USERNAME
        value: neondb_owner
      - key: SPRING_DATASOURCE_PASSWORD
        value: npg_mAJxKRSr03ap
      - key: GEMINI_API_KEY
        value: AIzaSyBR-6VZGjm_JPFCh8NHv-opGqsqE6kc1ko
  - type: web
    name: donation-system-frontend
    runtime: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://intelligent-food-donation-and-waste.onrender.com