services:
  - type: web
    name: donation-system-backend
    runtime: docker
    plan: free
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://db.rttbesxmqlwmzjpaxbmx.supabase.co:6543/postgres?user=postgres&password=iR7rtHU497ZBqoKI&sslmode=require
      - key: SPRING_DATASOURCE_USERNAME
        value: postgres
      - key: SPRING_DATASOURCE_PASSWORD
        value: iR7rtHU497ZBqoKI
      - key: GEMINI_API_KEY
        value: AIzaSyBR-6VZGjm_JPFCh8NHv-opGqsqE6kc1ko

  - type: web
    name: donation-system-frontend
    runtime: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://donation-system-backend.onrender.com